# Generated by Django 5.2.9 on 2026-01-15 22:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tags',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('aesthetic', models.CharField(blank=True, max_length=20)),
                ('specialty', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Cafe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=20)),
                ('address', models.CharField(blank=True, max_length=20)),
                ('location_x', models.DecimalField(decimal_places=6, max_digits=9)),
                ('location_y', models.DecimalField(decimal_places=6, max_digits=9)),
                ('price_level', models.IntegerField(choices=[(1, '0-100'), (2, '100-200'), (3, '200-300'), (4, '300+')], default=1)),
                ('atmosphere', models.CharField(blank=True, max_length=10)),
                ('wifi_type', models.IntegerField(choices=[(1, 'None'), (2, 'Voucher'), (3, 'Unli')], default=1)),
                ('socket_availability', models.BooleanField()),
                ('is_24_7', models.BooleanField()),
                ('raw_hours', models.CharField(blank=True, max_length=100)),
                ('open_time', models.TimeField(blank=True, null=True)),
                ('close_time', models.TimeField(blank=True, null=True)),
                ('tags', models.ManyToManyField(blank=True, related_name='cafes', to='cafes.tags')),
            ],
        ),
    ]
