# Generated by Django 5.2.9 on 2026-01-17 03:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cafes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cafe',
            name='thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='cafe_photos/'),
        ),
    ]
